FROM debian:buster

ARG kafka_version=3.5.0 \
    kafka_connect_version=3.5.0 \
    scala_version=2.13 \
    vcs_ref=unspecified \
    build_date=unspecified \
    UID=1000 \
    GID=1000 \
    USERNAME=kafka \
    BOOTSTRAP_SERVERS \
    GROUP_ID \
    KEY_CONVERTER \
    VALUE_CONVERTER \
    KEY_CONVERTER_SCHEMAS_ENABLE \
    VALUE_CONVERTER_SCHEMAS_ENABLE \
    OFFSET_STORAGE_TOPIC \
    CONFIG_STORAGE_TOPIC \
    STATUS_STORAGE_TOPIC \
    LISTENER_PORT \
    PLUGIN_PATH \
    CONFIG_PROVIDERS \
    CONFIG_PROVIDERS_FILE_CLASS \
    SSL_ENDPOINT_IDENTIFICATION_ALGORITHM \
    REQUEST_TIMEOUT_MS \
    RETRY_BACKOFF_MS \
    SECURITY.PROTOCOL \
    SSL_PROTOCOL \
    SSL_TRUSTSTORE_LOCATION \
    SSL_TRUSTSTORE_PASSWORD \
    SSL_KEYSTORE_LOCATION \
    SSL_KEYSTORE_PASSWORD \
    SSL_KEY_PASSWORD \
    CONSUMER_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM \
    CONSUMER_REQUEST_TIMEOUT_MS \
    CONSUMER_RETRY_BACKOFF_MS \
    CONSUMER_SECURITY_PROTOCOL \
    CONSUMER_SSL_PROTOCOL \
    CONSUMER_SSL_TRUSTSTORE_LOCATION \
    CONSUMER_SSL_TRUSTSTORE_PASSWORD \
    CONSUMER_SSL_KEYSTORE_LOCATION \
    CONSUMER_SSL_KEYSTORE_PASSWORD \
    CONSUMER_SSL_KEY_PASSWORD \
    PRODUCER_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM \
    PRODUCER_REQUEST_TIMEOUT_MS \
    PRODUCER_RETRY_BACKOFF_MS \
    PRODUCER_SECURITY_PROTOCOL \
    PRODUCER_SSL_PROTOCOL \
    PRODUCER_SSL_TRUSTSTORE_LOCATION \
    PRODUCER_SSL_TRUSTSTORE_PASSWORD \
    PRODUCER_SSL_KEYSTORE_LOCATION \
    PRODUCER_SSL_KEYSTORE_PASSWORD \
    PRODUCER_SSL_KEY_PASSWORD \
    SASL_JAAS_CONFIG \
    PRODUCER_SASL_JAAS_CONFIG \
    CONSUMER_SASL_JAAS_CONFIG \
    SASL_MECHANISM \
    PRODUCER_SASL_MECHANISM \
    CONSUMER_SASL_MECHANISM \
    SASL_USER \
    SASL_PASSWORD \
    KEY_CONVERTER_SCHEMA_REGISTRY_SSL_TRUSTSTORE_LOCATION \
    KEY_CONVERTER_SCHEMA_REGISTRY_SSL_KEYSTORE_LOCATION \
    KEY_CONVERTER_SCHEMA_REGISTRY_SSL_KEYSTORE_PASSWORD \
    KEY_CONVERTER_SCHEMA_REGISTRY_SSL_KEY_PASSWORD \
    KEY_CONVERTER_SCHEMA_REGISTRY_URL \
    KEY_CONVERTER_BASIC_AUTH_CREDENTIALS_SOURCE \
    KEY_CONVERTER_BASIC_AUTH_USER_INFO \
    KEY_CONVERTER_SCHEMA_REGISTRY_SSL_TRUSTSTORE_TYPE \
    VALUE_CONVERTER_SCHEMA_REGISTRY_SSL_TRUSTSTORE_LOCATION \
    VALUE_CONVERTER_SCHEMA_REGISTRY_SSL_KEYSTORE_LOCATION \
    VALUE_CONVERTER_SCHEMA_REGISTRY_SSL_KEYSTORE_PASSWORD \
    VALUE_CONVERTER_SCHEMA_REGISTRY_SSL_KEY_PASSWORD \
    VALUE_CONVERTER_SCHEMA_REGISTRY_URL \
    VALUE_CONVERTER_BASIC_AUTH_CREDENTIALS_SOURCE \
    VALUE_CONVERTER_BASIC_AUTH_USER_INFO \
    VALUE_CONVERTER_SCHEMA_REGISTRY_SSL_TRUSTSTORE_TYPE \
    SCHEMA_REGISTRY_URL \
    SCHEMA_REGISTRY_SSL_TRUSTSTORE_PASSWORD \
    SCHEMA_REGISTRY_SSL_TRUSTSTORE_LOCATION \
    SCHEMA_REGISTRY_SSL_KEYSTORE_PASSWORD \
    SCHEMA_REGISTRY_SSL_KEYSTORE_LOCATION \
    SCHEMA_REGISTRY_SSL_KEY_PASSWORD \
    SCHEMA_REGISTRY_BASIC_AUTH_CREDENTIALS_SOURCE \
    SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO \
    LISTENERS \
    REST_ADVERTISED_LISTENER \
    KAFKA_JMX_PORT \
    KAFKA_JMX_HOSTNAME \
    KAFKA_JMX_OPTS \
    BROKER_LISTENER_MODE \
    SCHEMA_REGISTRY_MODE \
    KEY_CONVERTER_SCHEMAS_ENABLE \
    VALUE_CONVERTER_SCHEMAS_ENABLE \
    KAFKA_HEAP_OPTS \
    KAFKA_OPTS

LABEL org.label-schema.name="kafka connect" \
      org.label-schema.description="Confluent Kafka Connect" \
      org.label-schema.build-date="${build_date}" \
      org.label-schema.vcs-url="https://github.com/Dwijad/Dockerize-Kafka-Connect.git" \
      org.label-schema.vcs-ref="${vcs_ref}" \
      org.label-schema.version="${scala_version}_${kafka_version}" \
      org.label-schema.schema-version="1.0" \
      maintainer="dwijad"

ENV KAFKA_VERSION=$kafka_version \
    SCALA_VERSION=$scala_version \
    KAFKA_HOME=/u01/cnfkfk \
    BOOTSTRAP_SERVERS=$BOOTSTRAP_SERVERS \
    GROUP_ID=$GROUP_ID \
    KEY_CONVERTER=$KEY_CONVERTER \
    VALUE_CONVERTER=$VALUE_CONVERTER \
    KEY_CONVERTER_SCHEMAS_ENABLE=$KEY_CONVERTER_SCHEMAS_ENABLE \
    VALUE_CONVERTER_SCHEMAS_ENABLE=$VALUE_CONVERTER_SCHEMAS_ENABLE \
    OFFSET_STORAGE_TOPIC=$OFFSET_STORAGE_TOPIC \
    CONFIG_STORAGE_TOPIC=$CONFIG_STORAGE_TOPIC \
    STATUS_STORAGE_TOPIC=$STATUS_STORAGE_TOPIC \
    PLUGIN_PATH=$PLUGIN_PATH \
    CONFIG_PROVIDERS=$CONFIG_PROVIDERS \
    CONFIG_PROVIDERS_FILE_CLASS=$CONFIG_PROVIDERS_FILE_CLASS \
    SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=$SSL_ENDPOINT_IDENTIFICATION_ALGORITHM \
    REQUEST_TIMEOUT_MS=$REQUEST_TIMEOUT_MS \
    RETRY_BACKOFF_MS=$RETRY_BACKOFF_MS \ 
    SECURITY_PROTOCOL=$SECURITY_PROTOCOL \
    SSL_PROTOCOL=$SSL_PROTOCOL \
    SSL_TRUSTSTORE_LOCATION=$SSL_TRUSTSTORE_LOCATION \
    SSL_TRUSTSTORE_PASSWORD=$SSL_TRUSTSTORE_PASSWORD \
    SSL_KEYSTORE_LOCATION=$SSL_KEYSTORE_LOCATION \
    SSL_KEYSTORE_PASSWORD=$SSL_KEYSTORE_PASSWORD \
    SSL_KEY_PASSWORD=$SSL_KEY_PASSWORD \
    CONSUMER_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=$CONSUMER_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM \
    CONSUMER_REQUEST_TIMEOUT_MS=$CONSUMER_REQUEST_TIMEOUT_MS \
    CONSUMER_RETRY_BACKOFF_MS=$CONSUMER_RETRY_BACKOFF_MS \
    CONSUMER_SECURITY_PROTOCOL=$CONSUMER_SECURITY_PROTOCOL \
    CONSUMER_SSL_PROTOCOL=$CONSUMER_SSL_PROTOCOL \
    CONSUMER_SSL_TRUSTSTORE_LOCATION=$CONSUMER_SSL_TRUSTSTORE_LOCATION \
    CONSUMER_SSL_TRUSTSTORE_PASSWORD=$CONSUMER_SSL_TRUSTSTORE_PASSWORD \
    CONSUMER_SSL_KEYSTORE_LOCATION=$CONSUMER_SSL_KEYSTORE_LOCATION \
    CONSUMER_SSL_KEYSTORE_PASSWORD=$CONSUMER_SSL_KEYSTORE_PASSWORD \
    CONSUMER_SSL_KEY_PASSWORD=$CONSUMER_SSL_KEY_PASSWORD \
    PRODUCER_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=$PRODUCER_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM  \
    PRODUCER_REQUEST_TIMEOUT_MS=$PRODUCER_REQUEST_TIMEOUT_MS \
    PRODUCER_RETRY_BACKOFF_MS=$PRODUCER_RETRY_BACKOFF_MS \
    PRODUCER_SECURITY_PROTOCOL=$PRODUCER_SECURITY_PROTOCOL \
    PRODUCER_SSL_PROTOCOL=$PRODUCER_SSL_PROTOCOL \
    PRODUCER_SSL_TRUSTSTORE_LOCATION=$PRODUCER_SSL_TRUSTSTORE_LOCATION \
    PRODUCER_SSL_TRUSTSTORE_PASSWORD=$PRODUCER_SSL_TRUSTSTORE_PASSWORD \
    PRODUCER_SSL_KEYSTORE_LOCATION=$PRODUCER_SSL_KEYSTORE_LOCATION \
    PRODUCER_SSL_KEYSTORE_PASSWORD=$PRODUCER_SSL_KEYSTORE_PASSWORD \
    PRODUCER_SSL_KEY_PASSWORD=$PRODUCER_SSL_KEY_PASSWORD \
    SASL_JAAS_CONFIG=$SASL_JAAS_CONFIG \
    PRODUCER_SASL_JAAS_CONFIG=$PRODUCER_SASL_JAAS_CONFIG \
    CONSUMER_SASL_JAAS_CONFIG=$CONSUMER_SASL_JAAS_CONFIG \
    SASL_MECHANISM=$SASL_MECHANISM \
    PRODUCER_SASL_MECHANISM=$PRODUCER_SASL_MECHANISM \
    CONSUMER_SASL_MECHANISM=$CONSUMER_SASL_MECHANISM \
    SASL_USER=$SASL_USER \
    SASL_PASSWORD=$SASL_PASSWORD \
    KEY_CONVERTER_SCHEMA_REGISTRY_SSL_TRUSTSTORE_LOCATION=$KEY_CONVERTER_SCHEMA_REGISTRY_SSL_TRUSTSTORE_LOCATION \
    KEY_CONVERTER_SCHEMA_REGISTRY_SSL_KEYSTORE_LOCATION=$KEY_CONVERTER_SCHEMA_REGISTRY_SSL_KEYSTORE_LOCATION \
    KEY_CONVERTER_SCHEMA_REGISTRY_SSL_KEYSTORE_PASSWORD=$KEY_CONVERTER_SCHEMA_REGISTRY_SSL_KEYSTORE_PASSWORD \
    KEY_CONVERTER_SCHEMA_REGISTRY_SSL_KEY_PASSWORD=$KEY_CONVERTER_SCHEMA_REGISTRY_SSL_KEY_PASSWORD \
    KEY_CONVERTER_SCHEMA_REGISTRY_URL=$KEY_CONVERTER_SCHEMA_REGISTRY_URL \
    KEY_CONVERTER_BASIC_AUTH_CREDENTIALS_SOURCE=$KEY_CONVERTER_BASIC_AUTH_CREDENTIALS_SOURCE \
    KEY_CONVERTER_BASIC_AUTH_USER_INFO=$KEY_CONVERTER_BASIC_AUTH_USER_INFO \
    KEY_CONVERTER_SCHEMA_REGISTRY_SSL_TRUSTSTORE_TYPE=$KEY_CONVERTER_SCHEMA_REGISTRY_SSL_TRUSTSTORE_TYPE \
    VALUE_CONVERTER_SCHEMA_REGISTRY_SSL_TRUSTSTORE_LOCATION=$VALUE_CONVERTER_SCHEMA_REGISTRY_SSL_TRUSTSTORE_LOCATION \
    VALUE_CONVERTER_SCHEMA_REGISTRY_SSL_KEYSTORE_LOCATION=$VALUE_CONVERTER_SCHEMA_REGISTRY_SSL_KEYSTORE_LOCATION \
    VALUE_CONVERTER_SCHEMA_REGISTRY_SSL_KEYSTORE_PASSWORD=$VALUE_CONVERTER_SCHEMA_REGISTRY_SSL_KEYSTORE_PASSWORD \
    VALUE_CONVERTER_SCHEMA_REGISTRY_SSL_KEY_PASSWORD=$VALUE_CONVERTER_SCHEMA_REGISTRY_SSL_KEY_PASSWORD \
    VALUE_CONVERTER_SCHEMA_REGISTRY_URL=$VALUE_CONVERTER_SCHEMA_REGISTRY_URL \
    VALUE_CONVERTER_BASIC_AUTH_CREDENTIALS_SOURCE=$VALUE_CONVERTER_BASIC_AUTH_CREDENTIALS_SOURCE \
    VALUE_CONVERTER_BASIC_AUTH_USER_INFO=$VALUE_CONVERTER_BASIC_AUTH_USER_INFO \
    VALUE_CONVERTER_SCHEMA_REGISTRY_SSL_TRUSTSTORE_TYPE=$VALUE_CONVERTER_SCHEMA_REGISTRY_SSL_TRUSTSTORE_TYPE \
    SCHEMA_REGISTRY_URL=$SCHEMA_REGISTRY_URL \
    SCHEMA_REGISTRY_SSL_TRUSTSTORE_PASSWORD=$SCHEMA_REGISTRY_SSL_TRUSTSTORE_PASSWORD \
    SCHEMA_REGISTRY_SSL_TRUSTSTORE_LOCATION=$SCHEMA_REGISTRY_SSL_TRUSTSTORE_LOCATION \
    SCHEMA_REGISTRY_SSL_KEYSTORE_PASSWORD=$SCHEMA_REGISTRY_SSL_KEYSTORE_PASSWORD \
    SCHEMA_REGISTRY_SSL_KEYSTORE_LOCATION=$SCHEMA_REGISTRY_SSL_KEYSTORE_LOCATION \
    SCHEMA_REGISTRY_SSL_KEY_PASSWORD=$SCHEMA_REGISTRY_SSL_KEY_PASSWORD \
    SCHEMA_REGISTRY_BASIC_AUTH_CREDENTIALS_SOURCE=$SCHEMA_REGISTRY_BASIC_AUTH_CREDENTIALS_SOURCE \
    SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO=$SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO \ 
    LISTENERS=$LISTENERS \
    REST_ADVERTISED_LISTENER=$REST_ADVERTISED_LISTENER \
    LISTENER_PORT=$LISTENER_PORT \
    KAFKA_JMX_PORT=$KAFKA_JMX_PORT \
    KAFKA_JMX_HOSTNAME=$KAFKA_JMX_HOSTNAME \
    KAFKA_JMX_OPTS=$KAFKA_JMX_OPTS \
    BROKER_LISTENER_MODE=$BROKER_LISTENER_MODE \
    SCHEMA_REGISTRY_MODE=$SCHEMA_REGISTRY_MODE \
    KEY_CONVERTER_SCHEMAS_ENABLE=$KEY_CONVERTER_SCHEMAS_ENABLE \
    VALUE_CONVERTER_SCHEMAS_ENABLE=$VALUE_CONVERTER_SCHEMAS_ENABLE \
    KAFKA_HEAP_OPTS=$KAFKA_HEAP_OPTS \
    KAFKA_OPTS=$KAFKA_OPTS

ENV PATH=${PATH}:${KAFKA_HOME}/bin
USER root
WORKDIR $KAFKA_HOME

RUN set -eux  \
    && apt-get update  \
    && apt-get upgrade -y  \
    && apt-get install -y --no-install-recommends vim jq net-tools curl wget zip unzip openssl ca-certificates  \
    && apt clean  \
    && apt autoremove -y  \
    && apt -f install  \
    && apt-get install -y --no-install-recommends netcat sudo \
    && mkdir -p $KAFKA_HOME  \
    && groupadd --gid $GID $USERNAME \
    && adduser --uid $UID --gid $GID --disabled-password --gecos "" kafka --home $KAFKA_HOME --shell /bin/bash \
    && sudo echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME \
    && cp -r /etc/skel/.[^.]* $KAFKA_HOME \
    && mkdir -p $KAFKA_HOME/java \
    && chown -R kafka:kafka /u01 \
    && chmod -R 755  $KAFKA_HOME 

USER kafka
WORKDIR $KAFKA_HOME

ADD --chown=kafka:kafka --chmod=755 https://packages.confluent.io/archive/7.5/confluent-community-7.5.3.tar.gz /u01/cnfkfk/
ADD --chown=kafka:kafka --chmod=755 https://download.oracle.com/java/17/archive/jdk-17.0.10_linux-x64_bin.tar.gz /u01/cnfkfk/
ADD --chown=kafka:kafka --chmod=755 https://d1i4a15mxbxib1.cloudfront.net/api/plugins/confluentinc/kafka-connect-jdbc/versions/10.7.4/confluentinc-kafka-connect-jdbc-10.7.4.zip /u01/cnfkfk/
ADD --chown=kafka:kafka --chmod=755 https://dlm.mariadb.com/3700566/Connectors/java/connector-java-3.3.2/mariadb-java-client-3.3.2.jar /u01/cnfkfk/ 
ADD --chown=kafka:kafka --chmod=755 https://repo1.maven.org/maven2/io/debezium/debezium-connector-mysql/2.4.2.Final/debezium-connector-mysql-2.4.2.Final-plugin.tar.gz /u01/cnfkfk/
ADD --chown=kafka:kafka --chmod=755 https://repo.maven.apache.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.20.0/jmx_prometheus_javaagent-0.20.0.jar /u01/cnfkfk/etc/kafka/
ADD --chown=kafka:kafka --chmod=755 config/kafka-connect.yml $KAFKA_HOME/etc/kafka

RUN mkdir -p $KAFKA_HOME/java && \
    tar -zx -C $KAFKA_HOME/java --strip-components=1 -f jdk-17.0.10_linux-x64_bin.tar.gz && \
    rm -f jdk-17.0.10_linux-x64_bin.tar.gz && \
    unzip confluentinc-kafka-connect-jdbc-10.7.4.zip && \
    mkdir -p $KAFKA_HOME/share/java/kafka-connect-jdbc && \
    mv confluentinc-kafka-connect-jdbc-10.7.4/lib/* $KAFKA_HOME/share/java/kafka-connect-jdbc/ && \
    rm -rf confluentinc* && \
    mv mariadb-java-client-3.3.2.jar $KAFKA_HOME/share/java/kafka-connect-jdbc/ && \
    tar -zx -C $KAFKA_HOME --strip-components=1 -f confluent-community-7.5.3.tar.gz && \
    rm -rf confluent* && \
    tar -zx -C $KAFKA_HOME/share/java/kafka-connect-jdbc --strip-components=1 -f debezium-connector-mysql-2.4.2.Final-plugin.tar.gz && \
    rm -rf debezium-connector-mysql-2.4.2.Final-plugin.tar.gz && \
    chown -R kafka:kafka $KAFKA_HOME && \
    mkdir -p $KAFKA_HOME/etc/ssl

ADD --chown=kafka:kafka --chmod=755 script/generate_pem_cert.sh $KAFKA_HOME/etc/ssl
ADD --chown=kafka:kafka --chmod=755 script/ca/ $KAFKA_HOME/etc/ssl/
ADD --chown=kafka:kafka --chmod=755 config/connect-log4j.properties $KAFKA_HOME/etc/kafka

WORKDIR $KAFKA_HOME

ENV PATH="${PATH}:$KAFKA_HOME/java/bin:$KAFKA_HOME/bin" 
ENV JAVA_HOME="$KAFKA_HOME/java"
ENV CLASSPATH="${CLASSPATH}:$KAFKA_HOME/share/java/kafka-connect-jdbc/*:$KAFKA_HOME/share/java/kafka/*"

WORKDIR $KAFKA_HOME/etc/ssl

RUN chmod u+x $KAFKA_HOME/etc/ssl/generate_pem_cert.sh \    
    && $KAFKA_HOME/etc/ssl/generate_pem_cert.sh  


WORKDIR $KAFKA_HOME
ADD --chown=kafka:kafka --chmod=755 script/start.sh $KAFKA_HOME


CMD ["/bin/bash"]


ENTRYPOINT ["/bin/bash" , "start.sh"]
