apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ksql-0
  name: ksql-0
spec:
  containers:
  - image: localhost:5000/ksql-docker:17
    imagePullPolicy: IfNotPresent
    name: ksql-0
    env:
    - name: SCHEMA_REGISTRY_MODE
      value: "HTTPS"
    - name: BROKER_LISTENER_MODE
      value: "SASL_SSL"
    - name: SASL_USER
      value: "user1"
    - name: SASL_PASSWORD
      value: "password"
    - name: AUTHENTICATION_REALM
      value: "KsqlServerProps"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
